services:
  postgres:
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"

  fastapi:
    environment:
      APP_ENV: development
      DEBUG: "true"
    volumes:
      - ./backend/api:/app
      - media_storage:/app/media
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000

  worker:
    environment:
      APP_ENV: development
      DEBUG: "true"
    volumes:
      - ./backend/api:/app

  signaling:
    environment:
      APP_ENV: development
      DEBUG: "true"
    volumes:
      - ./backend/signaling:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]
