"""
Schemas for messaging endpoints.

Tombstone design: soft-deleted messages are returned with is_deleted=True
and content/media_id scrubbed to None. The client renders "message deleted".
"""
from __future__ import annotations

import base64
from datetime import datetime
from typing import Literal
from uuid import UUID

from pydantic import BaseModel, ConfigDict, field_validator, model_validator

from app.schemas.media import MediaResponse
from app.schemas.user import UserPublic

MessageType = Literal["text", "image", "video", "audio", "document"]


# ── Requests ──────────────────────────────────────────────────────────────────

class SendMessageRequest(BaseModel):
    """
    client_id is the message PK — generated by the client (UUID v4).
    Re-submitting with the same client_id is idempotent (returns original).
    """
    client_id: UUID
    recipient_id: UUID
    message_type: MessageType
    content: str | None = None
    media_id: UUID | None = None
    reply_to_id: UUID | None = None

    @model_validator(mode="after")
    def check_content_or_media(self) -> "SendMessageRequest":
        if self.message_type == "text":
            if not self.content or not self.content.strip():
                raise ValueError("content is required for text messages")
        else:
            if self.media_id is None:
                raise ValueError("media_id is required for non-text messages")
        return self


class ReceiptRequest(BaseModel):
    message_ids: list[UUID]

    @field_validator("message_ids")
    @classmethod
    def validate_not_empty(cls, v: list[UUID]) -> list[UUID]:
        if not v:
            raise ValueError("message_ids must not be empty")
        return v


# ── Responses ─────────────────────────────────────────────────────────────────

class MessageResponse(BaseModel):
    """
    is_deleted=True means the message was soft-deleted; content, media_id, and
    media are always None in that case. The client should render "message deleted".
    media is populated when the message has an associated MediaFile; None for text.
    """
    model_config = ConfigDict(from_attributes=False)

    id: UUID
    conversation_id: UUID
    sender_id: UUID
    message_type: str
    content: str | None
    media_id: UUID | None
    media: MediaResponse | None = None   # populated if media_id is set
    reply_to_id: UUID | None
    status: str
    is_deleted: bool
    created_at: datetime
    updated_at: datetime | None


class ConversationResponse(BaseModel):
    model_config = ConfigDict(from_attributes=False)

    id: UUID
    other_user: UserPublic
    last_message: MessageResponse | None
    last_activity: datetime
    unread_count: int


class MessagePage(BaseModel):
    """
    Cursor-based page of messages, newest first (descending created_at).
    next_cursor is None when there are no older messages.
    The cursor encodes the created_at and id of the last returned message;
    pass it as the `cursor` query parameter to fetch the next page.
    """
    messages: list[MessageResponse]
    next_cursor: str | None


# ── Cursor helpers ─────────────────────────────────────────────────────────────

def encode_cursor(created_at: datetime, msg_id: UUID) -> str:
    raw = f"{created_at.isoformat()}|{msg_id}"
    return base64.urlsafe_b64encode(raw.encode()).decode()


def decode_cursor(cursor: str) -> tuple[datetime, UUID]:
    raw = base64.urlsafe_b64decode(cursor.encode()).decode()
    ts_str, id_str = raw.split("|", 1)
    return datetime.fromisoformat(ts_str), UUID(id_str)
