/// Mirror of backend/api/app/schemas/settings.py:NotificationPreferences.
///
/// Hand-written (no codegen) to match the rest of this codebase.
class NotificationPreferences {
  // Channels
  final bool messagesEnabled;
  final bool groupMessagesEnabled;
  final bool callsEnabled;
  final bool reactionNotifications;
  final bool mentionNotifications;

  // Behaviour
  final bool showPreview;
  final bool vibrate;
  final bool highPriorityNotifications;

  // Sounds (asset id, "system_default", or "none")
  final String messageSound;
  final String callRingtone;

  // Quiet hours (HH:MM, 24h)
  final bool quietHoursEnabled;
  final String quietHoursStart;
  final String quietHoursEnd;

  const NotificationPreferences({
    this.messagesEnabled = true,
    this.groupMessagesEnabled = true,
    this.callsEnabled = true,
    this.reactionNotifications = true,
    this.mentionNotifications = true,
    this.showPreview = true,
    this.vibrate = true,
    this.highPriorityNotifications = true,
    this.messageSound = 'system_default',
    this.callRingtone = 'system_default',
    this.quietHoursEnabled = false,
    this.quietHoursStart = '22:00',
    this.quietHoursEnd = '07:00',
  });

  factory NotificationPreferences.fromJson(Map<String, dynamic> json) =>
      NotificationPreferences(
        messagesEnabled: json['messages_enabled'] as bool? ?? true,
        groupMessagesEnabled: json['group_messages_enabled'] as bool? ?? true,
        callsEnabled: json['calls_enabled'] as bool? ?? true,
        reactionNotifications:
            json['reaction_notifications'] as bool? ?? true,
        mentionNotifications: json['mention_notifications'] as bool? ?? true,
        showPreview: json['show_preview'] as bool? ?? true,
        vibrate: json['vibrate'] as bool? ?? true,
        highPriorityNotifications:
            json['high_priority_notifications'] as bool? ?? true,
        messageSound: json['message_sound'] as String? ?? 'system_default',
        callRingtone: json['call_ringtone'] as String? ?? 'system_default',
        quietHoursEnabled: json['quiet_hours_enabled'] as bool? ?? false,
        quietHoursStart: json['quiet_hours_start'] as String? ?? '22:00',
        quietHoursEnd: json['quiet_hours_end'] as String? ?? '07:00',
      );

  Map<String, dynamic> toJson() => {
        'messages_enabled': messagesEnabled,
        'group_messages_enabled': groupMessagesEnabled,
        'calls_enabled': callsEnabled,
        'reaction_notifications': reactionNotifications,
        'mention_notifications': mentionNotifications,
        'show_preview': showPreview,
        'vibrate': vibrate,
        'high_priority_notifications': highPriorityNotifications,
        'message_sound': messageSound,
        'call_ringtone': callRingtone,
        'quiet_hours_enabled': quietHoursEnabled,
        'quiet_hours_start': quietHoursStart,
        'quiet_hours_end': quietHoursEnd,
      };

  NotificationPreferences copyWith({
    bool? messagesEnabled,
    bool? groupMessagesEnabled,
    bool? callsEnabled,
    bool? reactionNotifications,
    bool? mentionNotifications,
    bool? showPreview,
    bool? vibrate,
    bool? highPriorityNotifications,
    String? messageSound,
    String? callRingtone,
    bool? quietHoursEnabled,
    String? quietHoursStart,
    String? quietHoursEnd,
  }) =>
      NotificationPreferences(
        messagesEnabled: messagesEnabled ?? this.messagesEnabled,
        groupMessagesEnabled: groupMessagesEnabled ?? this.groupMessagesEnabled,
        callsEnabled: callsEnabled ?? this.callsEnabled,
        reactionNotifications:
            reactionNotifications ?? this.reactionNotifications,
        mentionNotifications:
            mentionNotifications ?? this.mentionNotifications,
        showPreview: showPreview ?? this.showPreview,
        vibrate: vibrate ?? this.vibrate,
        highPriorityNotifications:
            highPriorityNotifications ?? this.highPriorityNotifications,
        messageSound: messageSound ?? this.messageSound,
        callRingtone: callRingtone ?? this.callRingtone,
        quietHoursEnabled: quietHoursEnabled ?? this.quietHoursEnabled,
        quietHoursStart: quietHoursStart ?? this.quietHoursStart,
        quietHoursEnd: quietHoursEnd ?? this.quietHoursEnd,
      );
}

/// One row in MessageSoundsScreen. Keep [assetPath] null for the
/// pseudo-options "system_default" and "none".
class NotificationSound {
  final String id;
  final String label;
  final String? assetPath;

  const NotificationSound({
    required this.id,
    required this.label,
    this.assetPath,
  });
}

const kSystemDefaultSoundId = 'system_default';
const kNoneSoundId = 'none';

/// Static catalog. To add/rename sounds, drop the file into
/// flutter_app/assets/sounds/notifications/ and update this list.
/// The bundled WAVs are generated by _generate.py in that same folder.
const List<NotificationSound> kBundledNotificationSounds = [
  NotificationSound(
    id: 'chime',
    label: 'Chime',
    assetPath: 'sounds/notifications/chime.wav',
  ),
  NotificationSound(
    id: 'pop',
    label: 'Pop',
    assetPath: 'sounds/notifications/pop.wav',
  ),
  NotificationSound(
    id: 'ding',
    label: 'Ding',
    assetPath: 'sounds/notifications/ding.wav',
  ),
  NotificationSound(
    id: 'note',
    label: 'Note',
    assetPath: 'sounds/notifications/note.wav',
  ),
  NotificationSound(
    id: 'bubble',
    label: 'Bubble',
    assetPath: 'sounds/notifications/bubble.wav',
  ),
  NotificationSound(
    id: 'pulse',
    label: 'Pulse',
    assetPath: 'sounds/notifications/pulse.wav',
  ),
];

String labelForSoundId(String id) {
  if (id == kSystemDefaultSoundId) return 'System default';
  if (id == kNoneSoundId) return 'None';
  for (final s in kBundledNotificationSounds) {
    if (s.id == id) return s.label;
  }
  return id;
}
